// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Address struct {
	Street string `json:"street"`
	City   string `json:"city"`
	State  string `json:"state"`
	Zip    string `json:"zip"`
}

type Comment struct {
	ID            string     `json:"id"`
	UserID        string     `json:"userId"`
	PostID        string     `json:"postId"`
	Content       string     `json:"content"`
	Author        *User      `json:"author"`
	ParentComment *Comment   `json:"parentComment,omitempty"`
	Replies       []*Comment `json:"replies"`
}

type CreateAddress struct {
	Street string `json:"street"`
	City   string `json:"city"`
	State  string `json:"state"`
	Zip    string `json:"zip"`
}

type CreateCommentInput struct {
	PostID          string  `json:"postId"`
	UserID          string  `json:"userId"`
	Content         string  `json:"content"`
	ParentCommentID *string `json:"parentCommentId,omitempty"`
}

type CreatePost struct {
	UserID  string `json:"userId"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type CreateProfileInput struct {
	UserID    string   `json:"userId"`
	Bio       string   `json:"bio"`
	AvatarURL *string  `json:"avatarUrl,omitempty"`
	Interests []string `json:"interests"`
}

type CreateUserInput struct {
	Name     string         `json:"name"`
	Email    string         `json:"email"`
	Password string         `json:"password"`
	Address  *CreateAddress `json:"Address,omitempty"`
}

type Follow struct {
	ID        string `json:"id"`
	Follower  *User  `json:"follower"`
	Following *User  `json:"following"`
}

type FollowUserInput struct {
	UserID       string `json:"userId"`
	TargetUserID string `json:"targetUserId"`
}

type Mutation struct {
}

type Post struct {
	ID       string     `json:"id"`
	UserID   string     `json:"userId"`
	Title    string     `json:"title"`
	Content  string     `json:"content"`
	Author   *User      `json:"author"`
	Comments []*Comment `json:"comments"`
}

type Profile struct {
	ID        string   `json:"id"`
	UserID    string   `json:"userId"`
	Bio       string   `json:"bio"`
	AvatarURL *string  `json:"avatarUrl,omitempty"`
	Interests []string `json:"interests"`
}

type Query struct {
}

type User struct {
	ID           string   `json:"id"`
	Name         string   `json:"name"`
	Email        string   `json:"email"`
	Profile      *Profile `json:"profile,omitempty"`
	Posts        []*Post  `json:"posts"`
	Followers    []*User  `json:"followers"`
	Following    []*User  `json:"following"`
	Address      *Address `json:"Address"`
	Token        *string  `json:"token,omitempty"`
	RefreshToken *string  `json:"refreshToken,omitempty"`
}
